// COIN:NETWORK pairs with REAL per-user deposit addresses (NOWPayments).
// Must stay in sync with NOWPAY_CUR in cf-worker/_worker.js.
// Generated from NOWPayments /v1/full-currencies (payment-enabled, no memo/extra-id coins).
export const NOWPAY_SUPPORTED = new Set([
  '1INCH:ERC20', 'AAVE:ERC20', 'ADA:ADA', 'ALGO:ALGO',
  'APE:ERC20', 'APT:APT', 'ARB:ARBITRUM', 'ARPA:BEP20',
  'ARPA:ERC20', 'AXS:ERC20', 'BABYDOGE:BEP20', 'BAT:ERC20',
  'BCH:BCH', 'BEL:BEP20', 'BEL:ERC20', 'BNB:BEP20',
  'BOBA:ERC20', 'BTC:BTC', 'BTTC:TRC20', 'C98:BEP20',
  'CAKE:BEP20', 'CFX:BEP20', 'CHZ:ERC20', 'COTI:ERC20',
  'CTSI:ERC20', 'DAI:ARBITRUM', 'DAI:ERC20', 'DOGE:DOGE',
  'EGLD:BEP20', 'EGLD:EGLD', 'ETC:ETC', 'ETH:ARBITRUM',
  'ETH:BASE', 'ETH:BEP20', 'ETH:ERC20', 'ETH:ETH',
  'FIL:FIL', 'FLOKI:BEP20', 'FLOKI:ERC20', 'FUN:ERC20',
  'GALA:ERC20', 'GMX:ARBITRUM', 'GMX:AVAXC', 'GRT:ERC20',
  'HOT:ERC20', 'ILV:ERC20', 'INJ:BEP20', 'INJ:ERC20',
  'INJ:INJ', 'KNC:ERC20', 'LINK:ERC20', 'LTC:LTC',
  'MANA:ERC20', 'MATIC:ERC20', 'MATIC:POLYGON', 'NEAR:NEAR',
  'OKB:ERC20', 'OMG:ERC20', 'ONT:ONT', 'PEPE:ERC20',
  'QTUM:QTUM', 'SAND:ERC20', 'SHIB:BEP20', 'SHIB:ERC20',
  'SOL:SOL', 'SUI:SUI', 'SUPER:ERC20', 'TRX:TRC20',
  'TUSD:ERC20', 'TUSD:TRC20', 'UNI:ERC20', 'USDC:ALGO',
  'USDC:ARBITRUM', 'USDC:AVAXC', 'USDC:BASE', 'USDC:BEP20',
  'USDC:ERC20', 'USDC:OPTIMISM', 'USDC:POLYGON', 'USDC:SOL',
  'USDT:ARBITRUM', 'USDT:AVAXC', 'USDT:BEP20', 'USDT:CELO',
  'USDT:ERC20', 'USDT:OPTIMISM', 'USDT:POLYGON', 'USDT:SOL',
  'USDT:TRC20', 'VET:VET', 'WAVES:WAVES', 'WBTC:POLYGON',
  'WIN:TRC20', 'XMR:XMR', 'XRP:XRP', 'YFI:ERC20',
  'ZEC:ZEC', 'ZIL:ZIL',]);
