// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero/FramedTerminal.tsx": () => import("../components/mockups/hero/FramedTerminal.tsx"),
  "./components/mockups/hero/MastheadLedger.tsx": () => import("../components/mockups/hero/MastheadLedger.tsx"),
  "./components/mockups/trust-ribbon/Pillars.tsx": () => import("../components/mockups/trust-ribbon/Pillars.tsx"),
  "./components/mockups/trust-ribbon/TerminalTape.tsx": () => import("../components/mockups/trust-ribbon/TerminalTape.tsx"),
  "./components/mockups/trust-ribbon/VaultLedger.tsx": () => import("../components/mockups/trust-ribbon/VaultLedger.tsx")
};
