import type { LucideIcon } from 'lucide-react';
import {
  Crown, Users, UserPlus, Baby, Rocket, Gift, Pickaxe, Sparkles,
  CreditCard, Image as ImageIcon, Trophy, Wallet, Boxes, GraduationCap, HeartHandshake, ShieldCheck,
  TrendingUp, Shield, Zap, Globe, BookOpen, Award, Lock, Coins, Banknote, Ticket, Palette,
  LineChart, Percent, Building2, Headphones, CheckCircle2, Layers, Cpu, Smartphone, Brain, Star,
  BarChart3, Heart, Landmark, PiggyBank, ScrollText, FileCheck2, BadgeCheck, Globe2,
} from 'lucide-react';
import type { DeskTab } from '../components/DesktopNav';

export type MoreFeature = { icon: LucideIcon; title: string; desc: string };
export type MoreStep = { title: string; desc: string };
export type MoreStat = { value: string; label: string };
export type MoreFaq = { q: string; a: string };

export interface MorePageConfig {
  icon: LucideIcon;
  eyebrow: string;
  title: string;
  titleAccent?: string;
  subtitle: string;
  primaryCta: string;
  secondaryCta?: string;
  secondaryTab?: DeskTab;
  stats?: MoreStat[];
  features: MoreFeature[];
  steps?: MoreStep[];
  faq?: MoreFaq[];
  closingTitle?: string;
  closingDesc?: string;
}

export const MORE_PAGES: Record<string, MorePageConfig> = {
  vip: {
    icon: Crown,
    eyebrow: 'Basonce VIP & Institutional',
    title: 'A trusted partner for',
    titleAccent: 'VIPs & institutions',
    subtitle:
      'Unlock the lowest fees, dedicated account management, deep liquidity and institutional-grade tools built for high-volume traders, funds, market makers and corporates.',
    primaryCta: 'Apply for VIP',
    secondaryCta: 'View fee tiers',
    secondaryTab: 'markets',
    stats: [
      { value: '0.000%', label: 'Maker fees from' },
      { value: '$10B+', label: 'Daily liquidity' },
      { value: '24/7', label: 'Dedicated support' },
      { value: '9', label: 'VIP tiers' },
    ],
    features: [
      { icon: Percent, title: 'Lowest trading fees', desc: 'Tiered maker/taker discounts that drop as your 30-day volume and BNC balance grow.' },
      { icon: Headphones, title: 'Dedicated manager', desc: 'A personal account manager and priority 24/7 line for onboarding and execution.' },
      { icon: LineChart, title: 'Deep liquidity', desc: 'Access institutional order books, OTC desk and block trading with minimal slippage.' },
      { icon: Cpu, title: 'Powerful APIs', desc: 'Low-latency REST & WebSocket APIs with higher rate limits for automated strategies.' },
      { icon: Shield, title: 'Asset protection', desc: 'Cold-storage custody, proof-of-reserves and an insurance fund safeguarding your capital.' },
      { icon: Building2, title: 'Corporate accounts', desc: 'Multi-user sub-accounts, role permissions and consolidated reporting for your team.' },
    ],
    steps: [
      { title: 'Apply', desc: 'Submit your trading volume or institution details to start the VIP review.' },
      { title: 'Get verified', desc: 'Our team confirms your tier and sets up dedicated support within 24 hours.' },
      { title: 'Trade & save', desc: 'Enjoy reduced fees, deeper liquidity and white-glove service from day one.' },
    ],
    faq: [
      { q: 'How do I qualify for a VIP tier?', a: 'Tiers are based on your 30-day spot/futures volume and BNC holdings. Higher activity unlocks lower fees and more perks.' },
      { q: 'Is there an institutional onboarding process?', a: 'Yes. Funds, market makers and corporates get a tailored onboarding with KYB verification and a dedicated manager.' },
      { q: 'Do VIP benefits apply to both spot and futures?', a: 'Absolutely — fee discounts and liquidity access cover spot, margin and futures markets.' },
    ],
    closingTitle: 'Ready to trade like an institution?',
    closingDesc: 'Join thousands of VIP and institutional clients trading on Basonce every day.',
  },

  affiliate: {
    icon: Users,
    eyebrow: 'Basonce Affiliate Program',
    title: 'Earn up to',
    titleAccent: '50% commission',
    subtitle:
      'Partner with one of the world\u2019s fastest-growing exchanges. Share your link, bring active traders and earn lifetime commissions on every trade they make.',
    primaryCta: 'Become an affiliate',
    secondaryCta: 'Go to dashboard',
    secondaryTab: 'profile',
    stats: [
      { value: 'Up to 50%', label: 'Commission rate' },
      { value: 'Lifetime', label: 'Earnings' },
      { value: 'Daily', label: 'Payouts' },
      { value: '180+', label: 'Countries' },
    ],
    features: [
      { icon: Percent, title: 'High commission', desc: 'Earn up to 50% of the trading fees generated by every user you refer.' },
      { icon: Banknote, title: 'Daily payouts', desc: 'Commissions are settled to your account every day in real crypto.' },
      { icon: BarChart3, title: 'Real-time analytics', desc: 'Track clicks, sign-ups, conversions and earnings from one dashboard.' },
      { icon: Globe, title: 'Global reach', desc: 'Promote in 40+ languages to an audience across more than 180 countries.' },
      { icon: Layers, title: 'Marketing toolkit', desc: 'Ready-made banners, links and creatives to maximize your conversions.' },
      { icon: Headphones, title: 'Affiliate support', desc: 'A partner manager helps you scale your campaigns and earnings.' },
    ],
    steps: [
      { title: 'Sign up', desc: 'Join the affiliate program for free and get your unique referral link.' },
      { title: 'Share', desc: 'Promote Basonce on your site, social channels or community.' },
      { title: 'Earn', desc: 'Collect lifetime commissions on every trade your referrals make.' },
    ],
    faq: [
      { q: 'Who can join the affiliate program?', a: 'Content creators, communities, influencers and websites with crypto audiences are welcome to apply.' },
      { q: 'How much can I earn?', a: 'Commission rates reach up to 50% depending on your referred trading volume and tier.' },
      { q: 'When do I get paid?', a: 'Commissions are calculated and credited to your Basonce account daily.' },
    ],
    closingTitle: 'Turn your audience into income',
    closingDesc: 'Start earning lifetime commissions with the Basonce Affiliate Program today.',
  },

  referral: {
    icon: UserPlus,
    eyebrow: 'Basonce Referral',
    title: 'Invite friends,',
    titleAccent: 'earn together',
    subtitle:
      'Share your referral code with friends. When they trade, you both earn commission rebates and rewards \u2014 the more friends you invite, the more you earn.',
    primaryCta: 'Get referral link',
    secondaryCta: 'My rewards',
    secondaryTab: 'profile',
    stats: [
      { value: 'Up to 40%', label: 'Commission rebate' },
      { value: '2-way', label: 'Rewards' },
      { value: '\u221E', label: 'Invites' },
    ],
    features: [
      { icon: Gift, title: 'Two-way rewards', desc: 'You and your friend both receive a bonus when they start trading.' },
      { icon: Percent, title: 'Commission rebate', desc: 'Earn a rebate on the trading fees paid by every friend you refer.' },
      { icon: UserPlus, title: 'Unlimited invites', desc: 'There is no cap \u2014 invite as many friends as you like and keep earning.' },
      { icon: Smartphone, title: 'Easy sharing', desc: 'Share your code via link, QR or social media in a single tap.' },
    ],
    steps: [
      { title: 'Get your code', desc: 'Grab your unique referral link or QR code from your account.' },
      { title: 'Invite friends', desc: 'Send it to friends so they can register on Basonce.' },
      { title: 'Earn rewards', desc: 'Receive rebates and bonuses every time they trade.' },
    ],
    faq: [
      { q: 'How is the rebate calculated?', a: 'You earn a percentage of the trading fees your referred friends pay, credited automatically.' },
      { q: 'Is there a limit to how many people I can invite?', a: 'No \u2014 invite an unlimited number of friends and earn from each of them.' },
    ],
    closingTitle: 'Better together',
    closingDesc: 'Invite your friends to Basonce and grow your crypto rewards as a team.',
  },

  junior: {
    icon: Baby,
    eyebrow: 'Basonce Junior',
    title: 'Smart money habits,',
    titleAccent: 'parent-supervised',
    subtitle:
      'A safe, parent-supervised crypto account for kids and teens. Help the next generation learn about saving, investing and digital assets \u2014 with you in full control.',
    primaryCta: 'Set up a Junior account',
    secondaryCta: 'Learn the basics',
    secondaryTab: 'academy',
    stats: [
      { value: '100%', label: 'Parent control' },
      { value: 'Age 6\u201317', label: 'For young learners' },
      { value: 'Safe', label: 'Limited & monitored' },
    ],
    features: [
      { icon: Shield, title: 'Full parental control', desc: 'Parents approve every action and set spending and trading limits.' },
      { icon: BookOpen, title: 'Learn by doing', desc: 'Bite-sized lessons teach budgeting, saving and responsible investing.' },
      { icon: PiggyBank, title: 'Safe savings', desc: 'Kids build healthy habits in a sandboxed, low-risk environment.' },
      { icon: Lock, title: 'Privacy first', desc: 'Strong protections keep young users\u2019 data and funds secure.' },
    ],
    steps: [
      { title: 'Create the account', desc: 'Link a Junior profile to your verified parent account.' },
      { title: 'Set the rules', desc: 'Choose limits, allowances and which features are enabled.' },
      { title: 'Learn together', desc: 'Guide your child through lessons and supervised activity.' },
    ],
    faq: [
      { q: 'Who controls the Junior account?', a: 'The parent or guardian retains full control and must approve activity and limits.' },
      { q: 'Is it safe for children?', a: 'Yes \u2014 Junior accounts are sandboxed, limited and monitored, with privacy protections by default.' },
    ],
    closingTitle: 'Raise a financially confident generation',
    closingDesc: 'Give your child a safe first step into the world of digital assets.',
  },

  launchpool: {
    icon: Rocket,
    eyebrow: 'Basonce Launchpool',
    title: 'Stake to earn',
    titleAccent: 'new tokens',
    subtitle:
      'Lock your BNC or stablecoins to farm brand-new project tokens before they hit the open market. Zero trading risk \u2014 your staked assets stay yours.',
    primaryCta: 'Start farming',
    secondaryCta: 'View markets',
    secondaryTab: 'markets',
    stats: [
      { value: '0 risk', label: 'To principal' },
      { value: 'Daily', label: 'Reward drops' },
      { value: 'Flexible', label: 'Unstake anytime' },
    ],
    features: [
      { icon: Coins, title: 'Farm free tokens', desc: 'Earn allocations of new tokens just by staking assets you already hold.' },
      { icon: Shield, title: 'Principal protected', desc: 'Your staked assets are never traded \u2014 unstake them whenever you want.' },
      { icon: Rocket, title: 'Early access', desc: 'Get in on promising projects before they list on the open market.' },
      { icon: Zap, title: 'Daily rewards', desc: 'Rewards accrue and are distributed to your wallet every single day.' },
    ],
    steps: [
      { title: 'Pick a pool', desc: 'Choose an active Launchpool project to farm.' },
      { title: 'Stake assets', desc: 'Lock your BNC or stablecoins with flexible terms.' },
      { title: 'Collect tokens', desc: 'Harvest your new token rewards daily and unstake anytime.' },
    ],
    faq: [
      { q: 'Is my staked principal at risk?', a: 'No. Staked assets are only used to calculate rewards and can be withdrawn at any time.' },
      { q: 'How are rewards distributed?', a: 'Rewards are calculated per block and credited to your account daily.' },
    ],
    closingTitle: 'Put your idle crypto to work',
    closingDesc: 'Discover the next big project on Basonce Launchpool.',
  },

  megadrop: {
    icon: Gift,
    eyebrow: 'Basonce Megadrop',
    title: 'Quests & rewards in one',
    titleAccent: 'token launch platform',
    subtitle:
      'Lock tokens and complete Web3 quests to unlock boosted airdrop rewards from upcoming projects. The more you participate, the bigger your share.',
    primaryCta: 'Explore Megadrop',
    secondaryCta: 'Open Wallet',
    secondaryTab: 'wallet',
    stats: [
      { value: 'Boosted', label: 'Airdrop rewards' },
      { value: 'Web3', label: 'Quests' },
      { value: 'Early', label: 'Project access' },
    ],
    features: [
      { icon: Gift, title: 'Boosted airdrops', desc: 'Stack locked-token scores with quest scores for larger reward allocations.' },
      { icon: CheckCircle2, title: 'Fun Web3 quests', desc: 'Complete simple on-chain tasks to level up your rewards.' },
      { icon: Rocket, title: 'Early discovery', desc: 'Be first to access high-potential projects before they list.' },
      { icon: Star, title: 'Tiered scoring', desc: 'A transparent scoring system rewards committed participants more.' },
    ],
    steps: [
      { title: 'Lock tokens', desc: 'Subscribe by locking eligible tokens to earn a base score.' },
      { title: 'Do quests', desc: 'Complete Web3 quests to boost your total reward score.' },
      { title: 'Claim rewards', desc: 'Receive your airdrop allocation when the project goes live.' },
    ],
    faq: [
      { q: 'How are my rewards calculated?', a: 'Your final allocation combines your locked-token score and the quests you complete.' },
      { q: 'Do I keep my locked tokens?', a: 'Yes \u2014 locked tokens are returned to you after the subscription period ends.' },
    ],
    closingTitle: 'Earn more by doing more',
    closingDesc: 'Join Basonce Megadrop and turn participation into rewards.',
  },

  miningpool: {
    icon: Pickaxe,
    eyebrow: 'Basonce Mining Pool',
    title: 'Mine more with a',
    titleAccent: 'world-class pool',
    subtitle:
      'Connect your hardware to the Basonce Mining Pool for stable payouts, low fees and transparent statistics. Smart distribution maximizes your mining income.',
    primaryCta: 'Connect to pool',
    secondaryCta: 'Cloud mining',
    secondaryTab: 'mining',
    stats: [
      { value: 'FPPS', label: 'Payout method' },
      { value: 'Low', label: 'Pool fees' },
      { value: '99.9%', label: 'Uptime' },
      { value: 'Real-time', label: 'Hashrate stats' },
    ],
    features: [
      { icon: TrendingUp, title: 'Higher income', desc: 'Optimized reward distribution helps you earn more from every share.' },
      { icon: Percent, title: 'Low fees', desc: 'Competitive pool fees keep more of the rewards in your pocket.' },
      { icon: BarChart3, title: 'Transparent stats', desc: 'Monitor hashrate, workers and earnings in real time.' },
      { icon: Shield, title: 'Stable & secure', desc: 'Enterprise infrastructure delivers near-100% uptime and DDoS protection.' },
    ],
    steps: [
      { title: 'Create a worker', desc: 'Set up a mining account and add your worker.' },
      { title: 'Point your rig', desc: 'Connect your hardware to the pool with a single config.' },
      { title: 'Get paid', desc: 'Receive stable daily payouts straight to your account.' },
    ],
    faq: [
      { q: 'Which coins can I mine?', a: 'The pool supports major proof-of-work coins with FPPS-style payouts.' },
      { q: 'How often are payouts?', a: 'Earnings are settled daily once you pass the minimum payout threshold.' },
    ],
    closingTitle: 'Mine smarter, earn more',
    closingDesc: 'Connect to the Basonce Mining Pool and maximize your hashrate income.',
  },

  aipro: {
    icon: Sparkles,
    eyebrow: 'Basonce AI Pro',
    title: 'Your AI-powered',
    titleAccent: 'trading copilot',
    subtitle:
      'Let advanced AI analyze markets, surface opportunities and automate strategies for you. From smart signals to fully automated bots, trade with an edge \u2014 24/7.',
    primaryCta: 'Try AI Pro',
    secondaryCta: 'Open AI Bot',
    secondaryTab: 'aibot',
    stats: [
      { value: '24/7', label: 'Market monitoring' },
      { value: 'Real-time', label: 'AI signals' },
      { value: 'Auto', label: 'Strategy execution' },
    ],
    features: [
      { icon: Brain, title: 'Smart analysis', desc: 'AI scans hundreds of pairs to highlight setups and risk in real time.' },
      { icon: Zap, title: 'Automated strategies', desc: 'Deploy grid, DCA and trend bots that trade for you around the clock.' },
      { icon: LineChart, title: 'Actionable signals', desc: 'Receive clear, data-driven entries, exits and risk guidance.' },
      { icon: Shield, title: 'Risk controls', desc: 'Built-in stop-loss, take-profit and position sizing keep you protected.' },
    ],
    steps: [
      { title: 'Pick a strategy', desc: 'Choose an AI bot or build your own from templates.' },
      { title: 'Set parameters', desc: 'Define your budget, pairs and risk limits.' },
      { title: 'Let it run', desc: 'AI executes and optimizes your strategy automatically.' },
    ],
    faq: [
      { q: 'Do I need trading experience?', a: 'No \u2014 AI Pro offers ready-made strategies, while advanced users can fully customize them.' },
      { q: 'Are my funds safe?', a: 'Bots operate within your account with strict risk limits; you stay in control at all times.' },
    ],
    closingTitle: 'Trade with an unfair advantage',
    closingDesc: 'Put AI to work on your portfolio with Basonce AI Pro.',
  },

  pay: {
    icon: CreditCard,
    eyebrow: 'Basonce Pay',
    title: 'Send, receive &',
    titleAccent: 'spend crypto',
    subtitle:
      'A contactless, borderless and secure way to pay with crypto. Send funds to friends instantly with zero fees, or spend at millions of merchants worldwide.',
    primaryCta: 'Start using Pay',
    secondaryCta: 'Open Wallet',
    secondaryTab: 'wallet',
    stats: [
      { value: '0 fees', label: 'P2P transfers' },
      { value: 'Instant', label: 'Settlement' },
      { value: 'Global', label: 'Acceptance' },
    ],
    features: [
      { icon: Zap, title: 'Instant transfers', desc: 'Send crypto to anyone, anywhere in seconds with no network fees.' },
      { icon: Globe2, title: 'Spend worldwide', desc: 'Pay at millions of online and in-store merchants that accept crypto.' },
      { icon: Lock, title: 'Bank-grade security', desc: 'Every payment is protected with encryption and fraud monitoring.' },
      { icon: Smartphone, title: 'Pay by QR', desc: 'Scan to pay or get paid in a single tap, right from your phone.' },
    ],
    steps: [
      { title: 'Top up', desc: 'Fund your Pay balance from your Basonce wallet.' },
      { title: 'Send or scan', desc: 'Transfer to a contact or scan a merchant QR code.' },
      { title: 'Done', desc: 'Payments settle instantly with a confirmation receipt.' },
    ],
    faq: [
      { q: 'Are there fees to send money?', a: 'Peer-to-peer transfers between Basonce users are free and instant.' },
      { q: 'Where can I spend?', a: 'You can spend with any merchant that accepts Basonce Pay, online or in-store.' },
    ],
    closingTitle: 'The easiest way to pay with crypto',
    closingDesc: 'Move money the modern way with Basonce Pay.',
  },

  nft: {
    icon: ImageIcon,
    eyebrow: 'Basonce NFT',
    title: 'Discover, collect &',
    titleAccent: 'trade NFTs',
    subtitle:
      'Explore NFTs from creators worldwide. Buy, sell and showcase digital art, collectibles and gaming assets on a low-fee, high-performance marketplace.',
    primaryCta: 'Explore marketplace',
    secondaryCta: 'My collection',
    secondaryTab: 'wallet',
    stats: [
      { value: 'Low', label: 'Trading fees' },
      { value: 'Multi-chain', label: 'Support' },
      { value: '10k+', label: 'Creators' },
    ],
    features: [
      { icon: Palette, title: 'Curated drops', desc: 'Discover exclusive collections from top artists and rising creators.' },
      { icon: Percent, title: 'Low fees', desc: 'Trade with some of the lowest marketplace fees in the industry.' },
      { icon: Layers, title: 'Multi-chain', desc: 'Buy and sell NFTs across multiple leading blockchains.' },
      { icon: BadgeCheck, title: 'Verified creators', desc: 'Authenticity badges protect you from fakes and scams.' },
    ],
    steps: [
      { title: 'Connect wallet', desc: 'Link your Basonce wallet to the marketplace.' },
      { title: 'Browse & bid', desc: 'Discover collections and place bids or buy instantly.' },
      { title: 'Own it', desc: 'Your NFT lands in your wallet, ready to hold or resell.' },
    ],
    faq: [
      { q: 'Which blockchains are supported?', a: 'The marketplace supports several major chains so you can trade across ecosystems.' },
      { q: 'How do I know a collection is genuine?', a: 'Verified creators carry an authenticity badge to help you avoid counterfeits.' },
    ],
    closingTitle: 'Own a piece of the digital world',
    closingDesc: 'Start your collection on the Basonce NFT marketplace.',
  },

  fantoken: {
    icon: Trophy,
    eyebrow: 'Basonce Fan Token',
    title: 'Get closer to the',
    titleAccent: 'teams you love',
    subtitle:
      'Fan Tokens unlock an all-new fandom experience \u2014 vote in club polls, access exclusive rewards, VIP perks and unforgettable money-can\u2019t-buy experiences.',
    primaryCta: 'Explore Fan Tokens',
    secondaryCta: 'View markets',
    secondaryTab: 'markets',
    stats: [
      { value: 'Vote', label: 'On club decisions' },
      { value: 'VIP', label: 'Experiences' },
      { value: 'Exclusive', label: 'Rewards' },
    ],
    features: [
      { icon: CheckCircle2, title: 'Fan voting', desc: 'Have your say in official club polls and decisions.' },
      { icon: Gift, title: 'Exclusive rewards', desc: 'Unlock merch, NFTs and members-only giveaways.' },
      { icon: Star, title: 'VIP experiences', desc: 'Earn access to once-in-a-lifetime fan experiences.' },
      { icon: TrendingUp, title: 'Tradable assets', desc: 'Fan Tokens trade freely on the Basonce market.' },
    ],
    steps: [
      { title: 'Choose a team', desc: 'Find the Fan Token of the club or league you support.' },
      { title: 'Buy tokens', desc: 'Purchase Fan Tokens directly on Basonce.' },
      { title: 'Engage', desc: 'Vote, earn rewards and unlock VIP perks as a holder.' },
    ],
    faq: [
      { q: 'What can I do with Fan Tokens?', a: 'Vote in club polls, access rewards and VIP experiences, and trade them on the market.' },
      { q: 'Can I sell my Fan Tokens?', a: 'Yes \u2014 Fan Tokens are tradable on Basonce whenever you choose.' },
    ],
    closingTitle: 'Be more than a fan',
    closingDesc: 'Join the fandom revolution with Basonce Fan Tokens.',
  },

  wallet: {
    icon: Wallet,
    eyebrow: 'Basonce Wallet',
    title: 'Your gateway to',
    titleAccent: 'Web3',
    subtitle:
      'A secure, self-custody wallet to store, send and grow your crypto and NFTs. Access dApps, DeFi and the entire Web3 universe \u2014 all from one place.',
    primaryCta: 'Create wallet',
    secondaryCta: 'View assets',
    secondaryTab: 'assets',
    stats: [
      { value: 'Self-custody', label: 'You own the keys' },
      { value: 'Multi-chain', label: 'Networks' },
      { value: 'dApps', label: 'One-tap access' },
    ],
    features: [
      { icon: Lock, title: 'Self-custody', desc: 'Only you control your keys and your assets \u2014 always.' },
      { icon: Layers, title: 'Multi-chain', desc: 'Manage tokens and NFTs across many blockchains in one wallet.' },
      { icon: Globe, title: 'Web3 ready', desc: 'Connect to dApps, DeFi and marketplaces with a single tap.' },
      { icon: Shield, title: 'Built-in security', desc: 'Risk scanning and approvals protect you from malicious contracts.' },
    ],
    steps: [
      { title: 'Create or import', desc: 'Set up a new wallet or import an existing one securely.' },
      { title: 'Fund it', desc: 'Transfer crypto in from your exchange account or elsewhere.' },
      { title: 'Explore Web3', desc: 'Swap, stake and connect to dApps directly from your wallet.' },
    ],
    faq: [
      { q: 'What does self-custody mean?', a: 'You hold your own private keys, so you have full ownership and control of your funds.' },
      { q: 'Which networks are supported?', a: 'The wallet supports multiple leading blockchains and their tokens and NFTs.' },
    ],
    closingTitle: 'Step into Web3 with confidence',
    closingDesc: 'Create your Basonce Wallet and explore the decentralized world.',
  },

  chain: {
    icon: Boxes,
    eyebrow: 'Basonce Chain',
    title: 'Build on a fast,',
    titleAccent: 'low-cost blockchain',
    subtitle:
      'A high-performance, EVM-compatible blockchain for builders. Launch dApps, tokens and DeFi protocols with lightning-fast finality and near-zero gas fees.',
    primaryCta: 'Start building',
    secondaryCta: 'View ecosystem',
    secondaryTab: 'markets',
    stats: [
      { value: '<1s', label: 'Block time' },
      { value: '$0.001', label: 'Avg gas fee' },
      { value: 'EVM', label: 'Compatible' },
      { value: '1000+', label: 'dApps' },
    ],
    features: [
      { icon: Zap, title: 'Blazing fast', desc: 'Sub-second finality and high throughput for demanding apps.' },
      { icon: Percent, title: 'Near-zero fees', desc: 'Transactions cost a fraction of a cent, even at scale.' },
      { icon: Cpu, title: 'EVM compatible', desc: 'Deploy your Solidity contracts with the tools you already use.' },
      { icon: Globe2, title: 'Thriving ecosystem', desc: 'Tap into a fast-growing network of dApps, wallets and bridges.' },
    ],
    steps: [
      { title: 'Connect', desc: 'Add Basonce Chain to your wallet and bridge assets in.' },
      { title: 'Deploy', desc: 'Ship your smart contracts with standard EVM tooling.' },
      { title: 'Grow', desc: 'Launch to users and tap ecosystem grants and liquidity.' },
    ],
    faq: [
      { q: 'Is it compatible with Ethereum tools?', a: 'Yes \u2014 the chain is fully EVM-compatible, so MetaMask, Hardhat and more just work.' },
      { q: 'How low are the fees really?', a: 'Average transaction fees are a fraction of a cent, making micro-transactions viable.' },
    ],
    closingTitle: 'Build the future, on-chain',
    closingDesc: 'Launch your next project on Basonce Chain.',
  },

  academy: {
    icon: GraduationCap,
    eyebrow: 'Basonce Academy',
    title: 'Free crypto &',
    titleAccent: 'blockchain education',
    subtitle:
      'Learn crypto from zero to pro. Free articles, videos, courses and quizzes break down blockchain, trading and Web3 into simple, actionable lessons.',
    primaryCta: 'Start learning',
    secondaryCta: 'Browse markets',
    secondaryTab: 'markets',
    stats: [
      { value: '100%', label: 'Free forever' },
      { value: '500+', label: 'Lessons' },
      { value: 'All levels', label: 'Beginner to pro' },
    ],
    features: [
      { icon: BookOpen, title: 'Structured courses', desc: 'Follow guided learning paths from beginner to advanced.' },
      { icon: Brain, title: 'Bite-sized lessons', desc: 'Complex topics explained in clear, simple language.' },
      { icon: Award, title: 'Earn while you learn', desc: 'Complete quizzes to unlock rewards and certificates.' },
      { icon: Globe, title: 'Available everywhere', desc: 'Learn on any device, in many languages, completely free.' },
    ],
    steps: [
      { title: 'Pick a topic', desc: 'Choose what you want to learn \u2014 trading, DeFi, security and more.' },
      { title: 'Learn', desc: 'Work through articles, videos and interactive lessons.' },
      { title: 'Apply it', desc: 'Put your new knowledge to work on Basonce.' },
    ],
    faq: [
      { q: 'Is Basonce Academy really free?', a: 'Yes \u2014 all educational content is completely free, for every level.' },
      { q: 'Do I get certificates?', a: 'You can earn certificates and rewards by completing courses and quizzes.' },
    ],
    closingTitle: 'Knowledge is your best investment',
    closingDesc: 'Level up your crypto skills for free with Basonce Academy.',
  },

  charity: {
    icon: HeartHandshake,
    eyebrow: 'Basonce Charity',
    title: 'Giving made',
    titleAccent: 'transparent',
    subtitle:
      'Blockchain empowers charity to be transparent, efficient and traceable. Every donation is recorded on-chain, so you can see exactly where your help goes.',
    primaryCta: 'Donate now',
    secondaryCta: 'See impact',
    secondaryTab: 'home',
    stats: [
      { value: '100%', label: 'To recipients' },
      { value: 'On-chain', label: 'Transparency' },
      { value: 'Global', label: 'Causes' },
    ],
    features: [
      { icon: ScrollText, title: 'End-to-end tracking', desc: 'Follow every donation on-chain from donor to final recipient.' },
      { icon: Heart, title: '100% to causes', desc: 'Every cent of your donation reaches the people who need it.' },
      { icon: Globe2, title: 'Global impact', desc: 'Support disaster relief, education and humanitarian causes worldwide.' },
      { icon: Shield, title: 'Verified partners', desc: 'We work only with vetted, reputable charitable organizations.' },
    ],
    steps: [
      { title: 'Choose a cause', desc: 'Browse active campaigns and pick one that matters to you.' },
      { title: 'Donate crypto', desc: 'Give in a few taps directly from your Basonce account.' },
      { title: 'Track impact', desc: 'See your donation\u2019s on-chain journey and real-world results.' },
    ],
    faq: [
      { q: 'How much of my donation reaches the cause?', a: 'Basonce Charity is committed to passing 100% of donations through to recipients.' },
      { q: 'How is transparency guaranteed?', a: 'Every donation is recorded on the blockchain and publicly traceable.' },
    ],
    closingTitle: 'Crypto with a conscience',
    closingDesc: 'Make a transparent, traceable difference with Basonce Charity.',
  },

  travelrule: {
    icon: ShieldCheck,
    eyebrow: 'Basonce Travel Rule',
    title: 'Compliant transfers,',
    titleAccent: 'safer for everyone',
    subtitle:
      'The Travel Rule helps combat money laundering and terrorism financing by securely sharing required information for eligible crypto transfers \u2014 protecting users and the ecosystem.',
    primaryCta: 'Learn how it works',
    secondaryCta: 'Manage account',
    secondaryTab: 'profile',
    stats: [
      { value: 'FATF', label: 'Aligned' },
      { value: 'Encrypted', label: 'Data sharing' },
      { value: 'Global', label: 'Compliance' },
    ],
    features: [
      { icon: Landmark, title: 'Regulatory alignment', desc: 'Meets FATF Travel Rule requirements across major jurisdictions.' },
      { icon: Lock, title: 'Secure data sharing', desc: 'Required transfer information is exchanged using encrypted channels.' },
      { icon: FileCheck2, title: 'Clear process', desc: 'Simple prompts guide you when extra details are needed for a transfer.' },
      { icon: Shield, title: 'Safer ecosystem', desc: 'Helps prevent illicit activity and protects honest users.' },
    ],
    steps: [
      { title: 'Initiate transfer', desc: 'Start a withdrawal or deposit as usual.' },
      { title: 'Provide details', desc: 'If required, confirm beneficiary or originator information.' },
      { title: 'Complete safely', desc: 'Your transfer proceeds securely and in compliance.' },
    ],
    faq: [
      { q: 'Why am I asked for extra information?', a: 'Eligible transfers may require originator/beneficiary details under the Travel Rule to stay compliant.' },
      { q: 'Is my data safe?', a: 'Yes \u2014 required information is shared only through secure, encrypted compliance channels.' },
    ],
    closingTitle: 'Compliance that protects you',
    closingDesc: 'Basonce keeps your transfers secure and compliant worldwide.',
  },
};
