import React, { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Search, X, Clock, BookOpen } from 'lucide-react';

interface HotSearchOverlayProps {
  onClose: () => void;
  initialQuery?: string;
}

const TRENDING_ITEMS = [
  {
    rank: 1, text: 'US 401(k) Plans May Include Bitcoin', badge: 'HOT',
    readTime: '3 min', category: 'Regulation',
    article: `The US Department of Labor is reviewing proposed legislation that would allow 401(k) retirement plans to allocate a portion of funds into Bitcoin and other digital assets.

The bill, backed by a bipartisan group of senators, would permit plan administrators to offer crypto exposure as part of diversified retirement portfolios — up to a 10% cap.

**Why it matters:** Over $7.3 trillion is currently held in 401(k) plans across the US. Even a 1% allocation would inject tens of billions into Bitcoin.

Proponents argue that BTC's fixed supply of 21 million coins makes it a natural inflation hedge. Critics warn of volatility risks for near-retirees.

Major financial firms including Fidelity and BlackRock have already signaled readiness to offer compliant crypto products if the measure passes.

The legislation is expected to go to committee vote in Q2 2026. Markets have reacted positively, with BTC up 4.2% on the news.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 2, text: 'Google Warns Bitcoin Encryption Vulnerable to Quantum Computing', badge: null,
    readTime: '4 min', category: 'Technology',
    article: `Google's quantum computing division has published a whitepaper suggesting that current Bitcoin wallet encryption (ECDSA 256-bit) could theoretically be broken by sufficiently powerful quantum computers within 10–15 years.

The paper does not claim imminent threat — today's quantum machines are far too weak — but flags the need for post-quantum cryptographic standards in blockchain infrastructure.

**What Bitcoin developers say:** The Bitcoin Core team has been aware of this risk for years. BIP-360 (Pay-to-Quantum-Resistant-Hash) is under active discussion as a soft-fork upgrade path.

Importantly, wallets that have never exposed their public key (i.e., never spent from them) remain safe even under quantum attack. Only reused addresses are at risk.

Ethereum's Vitalik Buterin has also outlined a quantum-resistance roadmap. Most major L1 blockchains are monitoring the situation closely.

**Bottom line:** Not a crisis today, but a technical challenge the industry must solve over the next decade.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 3, text: 'Mined in America Act Targets China Decoupling', badge: 'HOT',
    readTime: '3 min', category: 'Policy',
    article: `The "Mined in America" Act, introduced in the US Senate, aims to provide tax incentives for Bitcoin miners that source hardware and energy domestically — effectively reducing dependence on Chinese-manufactured ASICs.

The bill includes a 30% tax credit for mining operations using US-made chips and renewable energy, and a 15% tariff on imported mining hardware from designated countries.

**Impact on mining industry:** US-based miners like Marathon Digital, Riot Platforms, and CleanSpark would benefit significantly. Analysts estimate the bill could shift 20–25% of global hash rate to the US within 3 years.

The legislation comes amid broader US-China tech decoupling efforts and bipartisan concern over national security implications of crypto infrastructure concentration.

**BNC mining note:** Basonce Exchange's KITE mining ecosystem uses cloud-based distributed infrastructure, inherently multi-regional and policy-resilient.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 4, text: 'Oil Prices Surge 60% as Hormuz Strait Closure Fears Rise', badge: null,
    readTime: '3 min', category: 'Macro',
    article: `Oil prices have surged to $142/barrel — a 60% increase since January — amid escalating tensions in the Persian Gulf and fears that Iran may restrict shipping through the Strait of Hormuz.

The Strait of Hormuz is the world's most critical oil chokepoint, with approximately 21 million barrels per day transiting it — roughly 20% of global oil trade.

**Crypto correlation:** Historically, energy price spikes have had mixed effects on Bitcoin. Higher energy costs increase mining difficulty and squeeze miner margins, but macro uncertainty often drives safe-haven demand into BTC.

In the past 30 days, BTC has outperformed gold by 3.2% amid the oil spike, suggesting institutions are treating digital assets as an alternative macro hedge.

**Altcoin watch:** Energy-focused tokens including ONDO, AAVE, and infrastructure DeFi protocols have seen increased volume as investors rotate into productive-yield assets.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 5, text: 'CLARITY Act Faces Industry Skepticism on DeFi Rules', badge: null,
    readTime: '4 min', category: 'Regulation',
    article: `The CLARITY Act, a comprehensive US crypto regulatory framework, has drawn criticism from DeFi developers and exchanges over proposed provisions that would classify many DeFi protocols as unregistered securities exchanges.

The bill attempts to divide regulatory jurisdiction between the SEC and CFTC — giving the SEC authority over tokens deemed securities and CFTC jurisdiction over commodities like BTC and ETH.

**The DeFi concern:** Section 4(b) of the bill would require "decentralized protocols" with over $50M in daily volume to register with the SEC — a process many argue is technically impossible for truly decentralized systems.

Uniswap, Aave, and Compound have all issued public statements opposing the current draft. The DeFi Education Fund estimates compliance costs could drive 60% of US DeFi activity offshore.

Supporters argue the bill provides long-overdue clarity and will attract institutional capital. Amendments are expected before any floor vote.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 6, text: 'Stablecoin Velocity Doubles Amid Payment Adoption Wave', badge: null,
    readTime: '3 min', category: 'Payments',
    article: `On-chain data shows stablecoin transaction velocity has doubled year-over-year, driven by surging adoption in B2B payments, cross-border remittances, and emerging market retail use.

USDT and USDC combined now process over $18 trillion in annualized volume — surpassing Visa's global transaction volume for the first time.

**Key drivers:** Fintech integrations (Stripe, PayPal, Shopify all now support USDC), and a wave of EM adoption in countries with unstable local currencies — particularly in Turkey, Nigeria, Argentina, and Southeast Asia.

**For traders:** High stablecoin velocity is a leading indicator of market activity. Historically, periods of peak stablecoin transfer volume precede major crypto market moves by 2–4 weeks.

**BNC/USDT:** Basonce Exchange USDT pairs benefit directly — higher stablecoin liquidity means tighter spreads and deeper order books across all trading pairs.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 7, text: 'Aave V4 Launches Hub-and-Spoke Architecture for Liquidity', badge: null,
    readTime: '3 min', category: 'DeFi',
    article: `Aave V4 has officially launched its new hub-and-spoke liquidity architecture, a major protocol upgrade that unifies liquidity across all supported chains through a central "Hub" on Ethereum mainnet.

Under the new model, individual chain deployments (Polygon, Arbitrum, Base, Avalanche) function as "Spokes" that communicate with the Hub via cross-chain messaging — enabling shared liquidity depth without bridging assets.

**Why it matters:** DeFi's biggest challenge has been liquidity fragmentation across chains. Aave V4 directly addresses this, potentially making it the deepest single lending market in crypto.

Early metrics are strong: $2.1B in TVL migrated within 48 hours of launch. Interest rates for USDC deposits dropped 40bps due to improved utilization efficiency.

**AAVE token:** Up 28% since the V4 launch announcement. Governance token holders receive a share of protocol fees, which are expected to increase significantly with higher cross-chain volume.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 8, text: 'AI Agent Trading Volume Explodes 2,800% in Q1 2026', badge: 'NEW',
    readTime: '4 min', category: 'AI & Crypto',
    article: `AI-powered autonomous trading agents have generated $2.8 trillion in DEX volume in Q1 2026, a 2,800% increase year-over-year, according to Dune Analytics data.

The explosion is driven by the proliferation of on-chain AI agent frameworks — including Virtuals Protocol, ai16z, and proprietary institutional systems — that can independently execute complex multi-step DeFi strategies 24/7.

**What AI agents do:** These bots can analyze order books, news sentiment, on-chain data, and macro signals simultaneously, executing arbitrage, yield farming, and directional trades without human intervention.

**Market impact:** AI agent activity now accounts for an estimated 34% of all DEX volume on Ethereum and Solana. This has tightened spreads dramatically on major pairs but also introduced new forms of front-running.

**Basonce AI Bot:** Our proprietary AI trading assistant offers signal alerts and strategy suggestions — helping retail users compete in an increasingly automated market.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 9, text: 'Altcoins Hit Record Lows Worse Than Previous Crypto Winters', badge: 'NEW',
    readTime: '3 min', category: 'Market',
    article: `An analysis of altcoin performance reveals that median drawdowns in the 2025-2026 cycle have exceeded those of the 2018 and 2022 crypto winters — with the average top-200 altcoin down 94% from its all-time high.

Despite Bitcoin reaching new highs above $95,000, capital has remained concentrated in BTC and a handful of large-cap assets (ETH, SOL, BNB), leaving the long tail of altcoins starved of liquidity.

**Structural reasons:** The rise of Bitcoin ETFs has channeled institutional capital directly into BTC, bypassing the alt market. Additionally, the proliferation of new token launches has diluted attention and capital.

**Opportunity or trap?** Contrarian analysts point to historically extreme valuations as a setup for a powerful alt season. Skeptics warn that many projects will never recover.

**BNC exception:** Basonce Exchange's native token BNC has significantly outperformed the altcoin market, benefiting from real utility, exchange fee buybacks, and growing ecosystem adoption.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
];

const ALPHA_ITEMS = [
  {
    rank: 1, text: 'EQ Token Surges 11,400% — Basonce Exchange Exclusive', badge: 'HOT',
    readTime: '3 min', category: 'Alpha',
    article: `EQ Token, exclusively listed on Basonce Exchange, has recorded a staggering 11,400% gain since its initial listing — making it one of the top-performing assets in the 2026 crypto cycle.

The token powers the EqualProtocol ecosystem, a decentralized identity and reputation layer built on zkSync. Its tokenomics feature a deflationary burn mechanism tied to protocol usage, with 40% of transaction fees used to buy and burn EQ.

**Why only on Basonce?** Basonce Exchange was the exclusive launchpad partner for EQ, giving our users first access at the ground floor. Early holders who bought at listing have seen extraordinary returns.

**Current utility:** EQ is used for governance, staking (current APY: 340%), and access to premium protocol features. The team has announced cross-chain expansion to Arbitrum in Q3 2026.

**Risk note:** High-gain assets carry high risk. Always size positions appropriately.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 2, text: 'KITE Launchpool Now Live — Zero-Fee Mining Rewards', badge: 'HOT',
    readTime: '2 min', category: 'Alpha',
    article: `The KITE Launchpool on Basonce Exchange is now live, offering zero-fee mining rewards to all participating users. KITE is the native utility token of the Basonce ecosystem.

**How it works:** Users who hold any balance on Basonce Exchange automatically qualify for KITE mining rewards. Higher balances and upgraded mining equipment yield more KITE per hour.

**Tokenomics:** Total supply: 1 billion KITE. 30% allocated to ecosystem mining rewards over 4 years. 20% to liquidity pools. No VC allocation — 100% community distributed.

**Current reward rates:**
- Basic mining: 0.5 KITE/hour
- ASIC Pro: 12 KITE/hour  
- Mining Farm Pro: 45 KITE/hour

**Upcoming:** KITE/USDT spot trading launches next quarter. Early miners will have a significant cost-basis advantage.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 3, text: 'Basonce Alpha: Top 3 Under-Radar Gems This Week', badge: 'NEW',
    readTime: '4 min', category: 'Alpha',
    article: `Our research team has identified three under-the-radar opportunities this week based on on-chain data, social sentiment, and technical analysis.

**#1 — POWERAI/USDT**
AI infrastructure token with real enterprise clients. Currently in accumulation phase. On-chain wallets > $100K have increased holdings by 34% in the past 7 days. Watch the $0.00045 support level.

**#2 — PAYAI/USDT**
Payments AI protocol with live integrations in 12 Southeast Asian markets. Volume up 180% week-over-week. Strong developer activity on GitHub (847 commits in 30 days).

**#3 — SGP/USDT**
Gaming infrastructure with a confirmed partnership with a top-10 mobile game studio (announcement expected Q2). Currently trading at 2021 lows despite improving fundamentals.

All three are available on Basonce Exchange. Always use proper risk management.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 4, text: 'EQL Staking Yields Hit 340% APY Amid Supply Squeeze', badge: null,
    readTime: '2 min', category: 'Alpha',
    article: `EQL staking pools on Basonce Exchange are currently offering 340% APY — among the highest yields in DeFi — driven by a combination of reduced circulating supply and increased protocol fee revenue.

A recent governance vote locked 62% of circulating EQL in a 6-month staking contract, creating an aggressive supply squeeze. With fewer tokens available for trading, buy pressure has intensified.

**Compounding advantage:** Daily reward payouts allow for auto-compounding, meaning an initial $1,000 stake would grow to approximately $4,400 over 12 months at current rates (assuming stable APY — which is not guaranteed).

**Risk factors:** APY is variable and depends on protocol revenue. Smart contract risk exists as with all DeFi staking. Staked tokens are subject to a 7-day unbonding period.

Available exclusively in the Earn section of Basonce Exchange.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 5, text: 'PUMP Token Distribution Schedule Announced for Q2', badge: null,
    readTime: '2 min', category: 'Alpha',
    article: `The PUMP token distribution schedule for Q2 2026 has been officially announced. Basonce Exchange is one of two platforms selected as official distribution partners.

**Distribution details:**
- Total Q2 allocation: 110 million PUMP tokens
- Eligible: All Basonce users who have completed KYC and held a balance for 30+ days
- Snapshot date: April 15, 2026
- Distribution date: May 1, 2026

**How to qualify:** Maintain any positive balance on Basonce Exchange. Higher balances receive proportionally larger allocations. Mining activity on the platform also boosts your allocation multiplier.

PUMP has a current market cap of $240M and strong community support. The project focuses on meme-economy infrastructure — providing launchpad and liquidity services for viral token launches.

Check the Campaigns section of the app for your estimated allocation.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 6, text: 'Basonce AI Bot Hits 94% Win Rate on BTC Futures', badge: 'NEW',
    readTime: '3 min', category: 'Alpha',
    article: `The Basonce AI trading bot has achieved a 94% win rate on BTC/USDT perpetual futures over the past 30 days, according to backtested and live-traded performance data.

The bot uses a multi-signal approach combining:
- Order book imbalance detection
- Funding rate arbitrage signals  
- Macro sentiment from news feeds
- On-chain miner behavior analysis

**Live results (last 30 days):**
- 847 trades executed
- 94.2% profitable
- Average profit per trade: 0.43%
- Maximum drawdown: 2.1%
- Total return: 87.4% (10x leverage, annualized ~1,050%)

**Important:** Past performance does not guarantee future results. The bot operates in a controlled risk environment. Users can access signal alerts (not auto-trading) in the AI Bot section.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 7, text: 'New TradFi Perp Pairs Added: TSLA, NVDA, AAPL', badge: null,
    readTime: '2 min', category: 'Alpha',
    article: `Basonce Exchange has added three new Traditional Finance (TradFi) perpetual futures pairs: TSLA/USDT, NVDA/USDT, and AAPL/USDT — allowing crypto-native users to trade US stocks 24/7 with up to 10x leverage.

**Why TradFi perps?** Traditional stock markets are closed on weekends and holidays. Our TradFi perpetuals track real-time stock prices through a combination of oracle feeds and after-hours market data, enabling round-the-clock trading.

**Key features:**
- Up to 10x leverage
- 0.02% maker / 0.05% taker fees
- Funding rate mechanism tracks spot premium/discount
- Settle in USDT — no stock brokerage account needed

**Market opportunity:** NVDA is up 340% year-to-date. TSLA has significant volatility around earnings and Elon news cycles. AAPL provides lower-volatility exposure to the US tech sector.

Available now in the Futures section.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
];

const SPOT_ITEMS = [
  {
    rank: 1, text: 'BTC/USDT — Breakout Confirmed Above $95K Resistance', badge: 'HOT',
    readTime: '3 min', category: 'Spot',
    article: `Bitcoin has confirmed a technical breakout above the critical $95,000 resistance level that had capped price action for 6 weeks. Volume on the breakout candle was 2.3x the 30-day average — a strong confirmation signal.

**Technical picture:** The weekly close above $95K projects a measured move target of $118,000–$125,000 based on the width of the prior consolidation range. RSI on the weekly is at 68 — elevated but not yet in extreme overbought territory.

**On-chain support:** Long-term holder supply is at a 2-year low, suggesting HODLers are not distributing despite the price rise. Exchange BTC reserves continue to decline — a bullish supply-side signal.

**Institutional flow:** BlackRock's IBIT Bitcoin ETF saw $1.2B in inflows in the past week — its highest since January 2025. Total spot ETF AUM now exceeds $95 billion.

**Trade BTC/USDT** on Basonce Exchange with the deepest liquidity and lowest fees.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 2, text: 'ETH/USDT — Pectra Upgrade Catalyst Incoming', badge: 'HOT',
    readTime: '3 min', category: 'Spot',
    article: `Ethereum's Pectra upgrade — the most significant protocol update since the Merge — is scheduled to activate within the next 3–4 weeks. Historically, major Ethereum upgrades have been positive catalysts for ETH price.

**What Pectra does:**
- EIP-7702: Allows regular wallets to temporarily act as smart contracts (account abstraction for all)
- EIP-7251: Increases max validator stake from 32 ETH to 2,048 ETH, improving staking efficiency
- EIP-7549: Reduces consensus layer bandwidth, improving node performance

**Historical precedent:** The Shapella upgrade (April 2023) and the Merge (September 2022) both saw ETH outperform BTC by 15–30% in the 30 days surrounding activation.

**ETH/BTC ratio:** Currently at 0.032, near multi-year lows. A catch-up trade is widely anticipated by ETH bulls.

**Trade ETH/USDT** on Basonce Exchange — available in spot and futures.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 3, text: 'SOL/USDT — Weekly Volume ATH on DEX Aggregators', badge: null,
    readTime: '2 min', category: 'Spot',
    article: `Solana-based DEX aggregators (Jupiter, Orca, Raydium) have recorded an all-time high in weekly trading volume — surpassing $48 billion in the past 7 days. This reflects Solana's dominance in on-chain trading activity.

**Network metrics:** Solana is processing 4,200 transactions per second on average, with peak throughput exceeding 65,000 TPS. Block times remain under 400ms.

**SOL fundamentals:** Staking yield at 7.2% APY. Validator count at an all-time high of 3,847. Developer activity (GitHub commits, new programs deployed) at a 12-month high.

**Price action:** SOL is forming a bull flag on the daily chart after a 40% run from the March lows. A breakout from the flag projects a target near $285.

**Trade SOL/USDT** on Basonce Exchange.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 4, text: 'DOGE/USDT — Elon X Post Sparks 18% Intraday Move', badge: 'NEW',
    readTime: '2 min', category: 'Spot',
    article: `Dogecoin surged 18% intraday after Elon Musk posted a DOGE-themed meme on X (formerly Twitter), reigniting retail interest in the original meme coin.

The post, which reached 340 million impressions within 6 hours, caused DOGE perpetual funding rates to spike to 0.15% per 8 hours — indicating heavy long positioning and elevated liquidation risk.

**Historical pattern:** Elon-driven DOGE pumps have historically retraced 60–80% within 48–72 hours as short-term traders take profits. However, 3 of the last 8 instances resulted in sustained moves when accompanied by high sustained volume.

**Current volume:** 24h volume is $8.2B — 6x the 30-day average. Whale wallets (>10M DOGE) have been net sellers into the pump according to on-chain data.

**Risk management note:** Meme coin volatility cuts both ways. Trade with strict stop-losses.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 5, text: 'WIF/USDT — Meme Supercycle Still Running Strong', badge: null,
    readTime: '2 min', category: 'Spot',
    article: `dogwifhat (WIF) continues to defy skeptics, maintaining strong price action as the leading Solana-native meme coin with a market cap now exceeding $4.8 billion.

**Why WIF persists:** Unlike many meme coins, WIF has developed genuine community infrastructure — a dedicated DAO treasury, active influencer base, and merchandise ecosystem. Brand recognition has reached mainstream levels.

**On-chain health:** Holder count growing week-over-week (+12% in past month). Top 20 wallets control only 18% of supply — relatively decentralized for a meme coin. Exchange reserves declining.

**Technical setup:** WIF is consolidating in a tight range between $2.85 and $3.20. Volume contraction suggests a major move is approaching. Breakout direction will be decisive.

**Solana ecosystem:** WIF benefits from the broader Solana bull narrative and DEX volume surge. Correlation with SOL is strong (0.82 30-day).

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 6, text: 'BONK/USDT — Solana Ecosystem Rotation Begins', badge: null,
    readTime: '2 min', category: 'Spot',
    article: `On-chain data suggests capital rotation is beginning within the Solana meme ecosystem — with BONK emerging as a beneficiary as traders look for lower market cap alternatives to WIF.

BONK, the community-driven dog meme coin airdropped to Solana NFT holders in December 2022, has seen wallet growth of +145,000 new holders in the past 30 days.

**BONK vs WIF:** BONK's fully diluted market cap is 40% lower than WIF's, offering more percentage upside in a bull scenario. However, BONK has a larger total supply and more complex tokenomics.

**Burn mechanism:** BONK's "BURNmas" events have permanently removed over 35 trillion tokens from circulation. The community continues to vote on additional burns.

**Integration:** BONK is accepted as a fee token on Solana's Jupiter DEX and integrated into several Solana DeFi protocols — giving it utility beyond pure speculation.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
  {
    rank: 7, text: 'PEPE/USDT — L2 Bridge Volume Triples in 48 Hours', badge: 'NEW',
    readTime: '2 min', category: 'Spot',
    article: `PEPE has seen a 3x surge in L2 bridge volume over the past 48 hours, as traders move the token from Ethereum mainnet to Arbitrum and Base in search of lower-fee trading environments.

**What this means:** L2 migration of PEPE liquidity is a bullish structural development. Lower fees enable more retail participation and higher frequency trading, which historically supports price discovery.

**Base ecosystem:** PEPE has become one of the top-10 most traded assets on Coinbase's Base L2. Farcaster (Base's social layer) communities have adopted PEPE as a cultural token.

**Market cap room:** PEPE's current market cap of $6.1B still leaves significant room relative to DOGE ($28B) and SHIB ($12B) if it maintains community momentum through this cycle's peak.

**Volatility alert:** PEPE can move 20–40% in single trading sessions. Position sizing and stop-losses are essential.

*This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.*`,
  },
];

const TABS = ['Trending', 'Alpha Search', 'Spot Search'] as const;

function rankColor(rank: number) {
  if (rank === 1) return '#F6465D';
  if (rank === 2) return '#F0B90B';
  if (rank === 3) return '#E8831D';
  return '#848E9C';
}

type AnyItem = typeof TRENDING_ITEMS[number];

export default function HotSearchOverlay({ onClose, initialQuery }: HotSearchOverlayProps) {
  const [query, setQuery] = useState(initialQuery?.replace(/^🔥+\s*/, '') ?? '');
  const [activeTab, setActiveTab] = useState<typeof TABS[number]>('Trending');
  const [visible, setVisible] = useState(false);
  const [selectedArticle, setSelectedArticle] = useState<AnyItem | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    requestAnimationFrame(() => setVisible(true));
    setTimeout(() => inputRef.current?.focus(), 200);
  }, []);

  const handleClose = () => {
    setVisible(false);
    setTimeout(onClose, 220);
  };

  const items = activeTab === 'Trending' ? TRENDING_ITEMS : activeTab === 'Alpha Search' ? ALPHA_ITEMS : SPOT_ITEMS;
  const filteredItems = query.trim()
    ? items.filter(i => i.text.toLowerCase().includes(query.toLowerCase()))
    : items;

  const renderArticle = (item: AnyItem) => (
    <div style={{ position: 'absolute', inset: 0, background: '#0B0E11', zIndex: 10, overflowY: 'auto' }}>
      {/* Article header */}
      <div style={{
        background: '#181A20', padding: '48px 16px 14px',
        display: 'flex', alignItems: 'center', gap: 10,
        position: 'sticky', top: 0, zIndex: 2,
        borderBottom: '1px solid #2B3139',
      }}>
        <button
          onClick={() => setSelectedArticle(null)}
          style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4, display: 'flex' }}
        >
          <ArrowLeft size={22} color="#fff" />
        </button>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{
              background: '#F0B90B22', color: '#F0B90B',
              fontSize: 10, fontWeight: 700, borderRadius: 4, padding: '2px 7px',
            }}>{item.category}</span>
            {item.badge && (
              <span style={{
                background: item.badge === 'HOT' ? '#F6465D22' : '#0ECB8122',
                color: item.badge === 'HOT' ? '#F6465D' : '#0ECB81',
                fontSize: 10, fontWeight: 800, borderRadius: 4, padding: '2px 6px',
              }}>{item.badge}</span>
            )}
          </div>
        </div>
      </div>

      {/* Article content */}
      <div style={{ padding: '20px 18px 48px' }}>
        <h1 style={{ color: '#fff', fontSize: 20, fontWeight: 800, lineHeight: 1.35, marginBottom: 12 }}>
          {item.text}
        </h1>

        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <Clock size={13} color="#848E9C" />
            <span style={{ color: '#848E9C', fontSize: 12 }}>{item.readTime} read</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <BookOpen size={13} color="#848E9C" />
            <span style={{ color: '#848E9C', fontSize: 12 }}>Basonce Research</span>
          </div>
        </div>

        <div style={{ height: 1, background: '#2B3139', marginBottom: 20 }} />

        {item.article.split('\n\n').map((para, i) => {
          if (para.startsWith('**') && para.endsWith('**')) {
            const text = para.slice(2, -2);
            return (
              <p key={i} style={{ color: '#F0B90B', fontWeight: 700, fontSize: 15, marginBottom: 12 }}>
                {text}
              </p>
            );
          }
          if (para.startsWith('*') && para.endsWith('*')) {
            return (
              <p key={i} style={{ color: '#4B5563', fontSize: 11, fontStyle: 'italic', marginTop: 24, lineHeight: 1.6 }}>
                {para.slice(1, -1)}
              </p>
            );
          }
          // Handle inline bold **text**
          const parts = para.split(/(\*\*[^*]+\*\*)/g);
          return (
            <p key={i} style={{ color: '#C6CBD4', fontSize: 15, lineHeight: 1.75, marginBottom: 14 }}>
              {parts.map((part, j) =>
                part.startsWith('**') && part.endsWith('**')
                  ? <strong key={j} style={{ color: '#fff', fontWeight: 700 }}>{part.slice(2, -2)}</strong>
                  : part
              )}
            </p>
          );
        })}
      </div>
    </div>
  );

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: '#0B0E11',
        transform: visible ? 'translateY(0)' : 'translateY(-100%)',
        transition: 'transform 0.22s cubic-bezier(0.4,0,0.2,1)',
        overflowY: 'auto',
      }}
    >
      {/* Header */}
      <div style={{ background: '#181A20', padding: '48px 16px 12px', display: 'flex', alignItems: 'center', gap: 10, position: 'sticky', top: 0, zIndex: 2 }}>
        <button onClick={handleClose} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4, display: 'flex' }}>
          <ArrowLeft size={22} color="#fff" />
        </button>

        <div style={{
          flex: 1, display: 'flex', alignItems: 'center', gap: 8,
          background: '#2B3139', borderRadius: 10, padding: '9px 12px',
        }}>
          <span style={{ fontSize: 15 }}>🔥</span>
          <input
            ref={inputRef}
            value={query}
            onChange={e => setQuery(e.target.value)}
            placeholder="Search coins, news, topics..."
            style={{
              flex: 1, background: 'none', border: 'none', outline: 'none',
              color: '#fff', fontSize: 14, caretColor: '#F0B90B',
            }}
          />
          {query ? (
            <button onClick={() => setQuery('')} style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', padding: 0 }}>
              <X size={16} color="#848E9C" />
            </button>
          ) : (
            <Search size={16} color="#848E9C" />
          )}
        </div>
      </div>

      <div style={{ padding: '16px 16px 0' }}>
        {/* You May Also Like */}
        <p style={{ color: '#fff', fontWeight: 700, fontSize: 15, marginBottom: 10 }}>You May Also Like</p>
        <div style={{
          background: '#1E2026', borderRadius: 12, padding: '12px 14px',
          display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20,
        }}>
          <div style={{
            width: 36, height: 36, borderRadius: '50%', background: 'linear-gradient(135deg,#5B5BFF,#9B59B6)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <span style={{ fontSize: 16 }}>📰</span>
          </div>
          <span style={{ color: '#fff', fontWeight: 600, fontSize: 14 }}>Today's Crypto Headlines</span>
        </div>

        {/* Hot Search Leaderboards */}
        <p style={{ color: '#fff', fontWeight: 700, fontSize: 15, marginBottom: 12 }}>Hot Search Leaderboards</p>

        {/* Tabs */}
        <div style={{ display: 'flex', gap: 8, marginBottom: 16, overflowX: 'auto', scrollbarWidth: 'none' }}>
          {TABS.map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                flexShrink: 0, position: 'relative',
                background: activeTab === tab ? '#2B3139' : 'none',
                border: 'none', borderRadius: 20, padding: '6px 14px',
                cursor: 'pointer', fontSize: 13,
                fontWeight: activeTab === tab ? 700 : 400,
                color: activeTab === tab ? '#fff' : '#848E9C',
              }}
            >
              {tab}
              {tab === 'Trending' && (
                <span style={{
                  position: 'absolute', top: -4, right: -2,
                  background: '#F0B90B', color: '#000', fontSize: 8,
                  fontWeight: 800, borderRadius: 4, padding: '0px 4px',
                }}>
                  Hot
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Items */}
        <div style={{ paddingBottom: 32 }}>
          {filteredItems.length === 0 && (
            <div style={{ padding: '40px 0', textAlign: 'center', color: '#848E9C', fontSize: 14 }}>
              No results for "{query}"
            </div>
          )}
          {filteredItems.map((item) => (
            <div
              key={item.rank}
              onClick={() => setSelectedArticle(item)}
              style={{
                display: 'flex', alignItems: 'center', gap: 14,
                padding: '13px 0', borderBottom: '1px solid #1E2026',
                cursor: 'pointer',
              }}
            >
              <span style={{
                minWidth: 20, textAlign: 'center',
                fontWeight: 800, fontSize: 15,
                color: rankColor(item.rank),
              }}>
                {item.rank}
              </span>
              <span style={{ flex: 1, color: '#E0E0E0', fontSize: 14, lineHeight: 1.4 }}>
                {item.text}
              </span>
              {item.badge && (
                <span style={{
                  background: item.badge === 'HOT' ? '#F6465D22' : '#0ECB8122',
                  color: item.badge === 'HOT' ? '#F6465D' : '#0ECB81',
                  fontSize: 10, fontWeight: 800, borderRadius: 4,
                  padding: '2px 6px', flexShrink: 0,
                }}>
                  {item.badge}
                </span>
              )}
            </div>
          ))}
        </div>

        <p style={{ color: '#4B5563', fontSize: 11, textAlign: 'center', paddingBottom: 24, lineHeight: 1.5 }}>
          This content is generated by AI and could be inaccurate. Please DYOR. Not financial advice.
        </p>
      </div>

      {/* Article detail overlay */}
      {selectedArticle && renderArticle(selectedArticle)}
    </div>
  );
}
